# Generated by Django 4.0.3 on 2023-06-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('picture_url', models.CharField(max_length=150)),
                ('bin', models.CharField(max_length=150)),
            ],
        ),
    ]
